### ISSUE TITLE
Data Wrangling

### ISSUE THREAD

**Issue by DiaCheck-C242-PS207** [DiaCheck-C242-PS207/DiaCheck-ML#2]

**Comment by DiaCheck-C242-PS207** [comment]
Bang tolong buat data wrangling sama visualizationnya yaa :D

**Comment by wahyuwinanta** [comment]
https://colab.research.google.com/drive/1LIa84_Fu7Yti_2aAuB78D_BXHvzY4_D2

Mas tolong coba dibenerin lagi

**Comment by DiaCheck-C242-PS207** [comment]
Ok Thanks ya

**Comment by wahyuwinanta** [comment]
Itu kurangnya apa ya mas...
